name: Save Godot build cache
description: Save Godot build cache.
inputs:
  cache-name:
    description: The cache base name (job name by default).
    default: ${{ github.job }}
  scons-cache:
    description: The SCons cache path.
    default: ${{ github.workspace }}/.scons_cache/
  purge-cache-script:
    description: Path to purge_cache.py
    required: false
    default: misc/scripts/purge_cache.py

runs:
  using: composite
  steps:
    - name: Ensure CACHE_TIMESTAMP
      shell: sh
      run: |
        if [ -z "${CACHE_TIMESTAMP}" ]; then
          echo "CACHE_TIMESTAMP empty — setting to 1 hour ago"
          echo "CACHE_TIMESTAMP=$(python3 -c 'import time; print(int(time.time())-3600)')" >> $GITHUB_ENV
        else
          echo "CACHE_TIMESTAMP exists: $CACHE_TIMESTAMP"
        fi

    - name: Purge files before timestamp
      shell: sh
      run: python3 ${{ inputs.purge-cache-script }} ${{ env.CACHE_TIMESTAMP }} "${{ inputs.scons-cache }}"

    - name: Check existing cache (lookup only)
      uses: actions/cache/restore@v5
      id: cache-check
      with:
        path: ${{ inputs.scons-cache }}
        key: ${{ inputs.cache-name }}|${{ github.ref_name }}
        lookup-only: true

    - name: Save SCons cache directory
      if: steps.cache-check.outputs.cache-matched-key == ''
      uses: actions/cache/save@v5
      with:
        path: ${{ inputs.scons-cache }}
        key: ${{ inputs.cache-name }}|${{ github.ref_name }}|${{ github.sha }}
        compression: zstd

    - name: Skip saving cache (already exists)
      if: steps.cache-check.outputs.cache-matched-key != ''
      shell: sh
      run: echo "Cache already exists for key ${{ inputs.cache-name }}|${{ github.ref_name }}; skipping save."
