name: Restore Godot build cache
description: Restore Godot build cache.
inputs:
  cache-name:
    description: The cache base name (job name by default).
    default: ${{ github.job }}
  scons-cache:
    description: The SCons cache path.
    default: ${{ github.workspace }}/.scons_cache/

outputs:
  cache-matched-key:
    description: Key of the cache that was restored (primary or restore-keys)
    value: ${{ steps.cache-ping.outputs.cache-matched-key }}
  cache-hit:
    description: 'Whether an exact cache hit occurred for the primary key'
    value: ${{ steps.cache-ping.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Restore default cache
      uses: actions/cache/restore@v5
      id: cache-ping
      with:
        path: ${{ inputs.scons-cache }}
        key: ${{ inputs.cache-name }}|${{ github.event.repository.default_branch }}|${{ github.sha }}
        restore-keys: ${{ inputs.cache-name }}|${{ github.event.repository.default_branch }}

    - name: Log default cache files
      if: steps.cache-ping.outputs.cache-matched-key && github.ref_name != github.event.repository.default_branch
      shell: sh
      run: find "${{ inputs.scons-cache }}" >> redundant.txt

    - name: Restore local cache
      uses: actions/cache/restore@v5
      if: github.ref_name != github.event.repository.default_branch
      with:
        path: ${{ inputs.scons-cache }}
        key: ${{ inputs.cache-name }}|${{ github.ref_name }}|${{ github.sha }}
        restore-keys: ${{ inputs.cache-name }}|${{ github.ref_name }}

    - name: Store unix timestamp
      shell: sh
      run: echo "CACHE_TIMESTAMP=$(date +%s)" >> $GITHUB_ENV
